//PROFILE ACTION TYPES
export const NAVIGATE_PROFILE = 'NAVIGATE_PROFILE';
export const FETCH_SESSION_DATA = 'FETCH_SESSION_DATA';
export const TOGGLE_APP_NAV_VIEWABLE = 'TOGGLE_APP_NAV_VIEWABLE';
export const OPEN_APP_NOTIF = 'OPEN_APP_NOTIF';
export const CLOSE_APP_NOTIF = 'CLOSE_APP_NOTIF';
