//CLOUD ACTION TYPES
export const NAVIGATE_APP = 'NAVIGATE_APP';
export const NAVIGATE_CLOUD = 'NAVIGATE_CLOUD';

//USER ACTION TYPES
export const FETCH_SESSION_DATA = 'FETCH_SESSION_DATA';
export const FETCH_USER_COMPANY_NAME = 'FETCH_USER_COMPANY_NAME';

//ACCOUNT ACTION TYPES
export const NAVIGATE_ACCOUNT = 'NAVIGATE_ACCOUNT';
export const NAVIGATE_ACCOUNT_PAGE_SECTION = 'NAVIGATE_ACCOUNT_PAGE_SECTION';

//CLIENT ACTION TYPES
export const TOGGLE_CLIENT_PAGE_SECTION = 'TOGGLE_CLIENT_PAGE_SECTION';
export const UPDATE_CLIENT_SEARCH_VALUE = 'UPDATE_CLIENT_SEARCH_VALUE';
export const CURRENT_CLIENT_DETAILS = 'CURRENT_CLIENT_DETAILS';
export const SET_CLIENT_SEARCH_OPTIONS = 'SET_CLIENT_SEARCH_OPTIONS';
export const SET_CURRENT_CLIENT_DETAILS = 'SET_CURRENT_CLIENT_DETAILS';
export const SET_CLIENT_SEARCH_PAGINATION_OPTIONS = 'SET_CLIENT_SEARCH_PAGINATION_OPTIONS';
export const ADD_RECENT_CLIENT_ACCOUNT = 'ADD_RECENT_CLIENT_ACCOUNT';
